-- Auto-generated source mapping from AtlasLoot TableRegister
-- Maps AtlasLoot table IDs to dungeon/raid names (not boss names)
-- Total mappings: 641

BISListSourceMap = {
    -- Abyssal Council
    ["AbyssalDukes"] = "Abyssal Council",
    ["AbyssalLords"] = "Abyssal Council",
    ["AbyssalTemplars"] = "Abyssal Council",

    -- Alterac Valley
    ["AVKorrak"] = "Alterac Valley",
    ["AVLokholarIvus"] = "Alterac Valley",
    ["AVRepExalted"] = "Alterac Valley",
    ["AVRepFriendly"] = "Alterac Valley",
    ["AVRepHonored"] = "Alterac Valley",
    ["AVRepRevered"] = "Alterac Valley",

    -- Arathi Basin
    ["ABRepExalted"] = "Arathi Basin",
    ["ABRepFriendly"] = "Arathi Basin",
    ["ABRepHonored2029"] = "Arathi Basin",
    ["ABRepHonored3039"] = "Arathi Basin",
    ["ABRepHonored4049"] = "Arathi Basin",
    ["ABRepHonored5059"] = "Arathi Basin",
    ["ABRepRevered2029"] = "Arathi Basin",
    ["ABRepRevered3039"] = "Arathi Basin",
    ["ABRepRevered4049"] = "Arathi Basin",
    ["ABRepRevered5059"] = "Arathi Basin",

    -- Argent Dawn
    ["Argent1"] = "Argent Dawn",

    -- Azshara
    ["AAzuregos"] = "Azshara",
    ["ASpiritA"] = "Azshara",
    ["Clackora"] = "Azshara",

    -- Black Morass
    ["COTBMAntnormi"] = "Black Morass",
    ["COTBMChronar"] = "Black Morass",
    ["COTBMDriftingAvatar"] = "Black Morass",
    ["COTBMEpidamu"] = "Black Morass",
    ["COTBMInfiniteChromie"] = "Black Morass",
    ["COTBMMossheart"] = "Black Morass",
    ["COTBMRotmaw"] = "Black Morass",
    ["COTBMTimeLordEpochronos"] = "Black Morass",
    ["COTTrash"] = "Black Morass",

    -- Blackfathom Deeps
    ["BFDAkumai"] = "Blackfathom Deeps",
    ["BFDBaronAquanis"] = "Blackfathom Deeps",
    ["BFDGelihast"] = "Blackfathom Deeps",
    ["BFDGhamoora"] = "Blackfathom Deeps",
    ["BFDLadySarevess"] = "Blackfathom Deeps",
    ["BFDOldSerrakis"] = "Blackfathom Deeps",
    ["BFDTrash"] = "Blackfathom Deeps",
    ["BFDTwilightLordKelris"] = "Blackfathom Deeps",
    ["BFDVelthelaxx"] = "Blackfathom Deeps",

    -- Blackrock Depths
    ["BRDAnubshiah"] = "Blackrock Depths",
    ["BRDBSPlans"] = "Blackrock Depths",
    ["BRDBaelGar"] = "Blackrock Depths",
    ["BRDEmperorDagranThaurissan"] = "Blackrock Depths",
    ["BRDEviscerator"] = "Blackrock Depths",
    ["BRDFineousDarkvire"] = "Blackrock Depths",
    ["BRDFlamelash"] = "Blackrock Depths",
    ["BRDForgewright"] = "Blackrock Depths",
    ["BRDGeneralAngerforge"] = "Blackrock Depths",
    ["BRDGolemLordArgelmach"] = "Blackrock Depths",
    ["BRDGorosh"] = "Blackrock Depths",
    ["BRDGrizzle"] = "Blackrock Depths",
    ["BRDGuzzler"] = "Blackrock Depths",
    ["BRDHedrum"] = "Blackrock Depths",
    ["BRDHighInterrogatorGerstahn"] = "Blackrock Depths",
    ["BRDHoundmaster"] = "Blackrock Depths",
    ["BRDLordIncendius"] = "Blackrock Depths",
    ["BRDLordRoccor"] = "Blackrock Depths",
    ["BRDLyceum"] = "Blackrock Depths",
    ["BRDMagmus"] = "Blackrock Depths",
    ["BRDOkthor"] = "Blackrock Depths",
    ["BRDPanzor"] = "Blackrock Depths",
    ["BRDPrincess"] = "Blackrock Depths",
    ["BRDPyromancerLoregrain"] = "Blackrock Depths",
    ["BRDPyron"] = "Blackrock Depths",
    ["BRDTheVault"] = "Blackrock Depths",
    ["BRDTheldren"] = "Blackrock Depths",
    ["BRDTomb"] = "Blackrock Depths",
    ["BRDTrash"] = "Blackrock Depths",
    ["BRDVerek"] = "Blackrock Depths",
    ["BRDWarderStilgiss"] = "Blackrock Depths",

    -- Blackwing Lair
    ["BWLChromaggus"] = "Blackwing Lair",
    ["BWLEbonroc"] = "Blackwing Lair",
    ["BWLFiremaw"] = "Blackwing Lair",
    ["BWLFlamegor"] = "Blackwing Lair",
    ["BWLLashlayer"] = "Blackwing Lair",
    ["BWLNefarian"] = "Blackwing Lair",
    ["BWLRazorgore"] = "Blackwing Lair",
    ["BWLTrashMobs"] = "Blackwing Lair",
    ["BWLVaelastrasz"] = "Blackwing Lair",

    -- Blasted Lands
    ["KKazzak"] = "Blasted Lands",

    -- Blood Ring
    ["BRRepExalted"] = "Blood Ring",
    ["BRRepFriendly"] = "Blood Ring",
    ["BRRepHonored"] = "Blood Ring",
    ["BRRepRevered"] = "Blood Ring",
    ["BRRepTokens"] = "Blood Ring",

    -- Cenarion Circle
    ["Cenarion1"] = "Cenarion Circle",
    ["Cenarion2"] = "Cenarion Circle",
    ["Cenarion3"] = "Cenarion Circle",
    ["Cenarion4"] = "Cenarion Circle",

    -- Deadwind Pass
    ["Reaver"] = "Deadwind Pass",

    -- Desolace
    ["Concavius"] = "Desolace",

    -- Dire Maul
    ["DMTome"] = "Dire Maul",

    -- Dire Maul (East)
    ["DMEAlzzin"] = "Dire Maul (East)",
    ["DMEHydro"] = "Dire Maul (East)",
    ["DMEIsalien"] = "Dire Maul (East)",
    ["DMELethtendris"] = "Dire Maul (East)",
    ["DMEPimgib"] = "Dire Maul (East)",
    ["DMEPusillin"] = "Dire Maul (East)",
    ["DMEShard"] = "Dire Maul (East)",
    ["DMETrash"] = "Dire Maul (East)",
    ["DMEZevrimThornhoof"] = "Dire Maul (East)",

    -- Dire Maul (North)
    ["DMNCaptainKromcrush"] = "Dire Maul (North)",
    ["DMNChoRush"] = "Dire Maul (North)",
    ["DMNGuardFengus"] = "Dire Maul (North)",
    ["DMNGuardMoldar"] = "Dire Maul (North)",
    ["DMNGuardSlipkik"] = "Dire Maul (North)",
    ["DMNKingGordok"] = "Dire Maul (North)",
    ["DMNStomperKreeg"] = "Dire Maul (North)",
    ["DMNTRIBUTERUN"] = "Dire Maul (North)",
    ["DMNThimblejack"] = "Dire Maul (North)",
    ["DMNTrash"] = "Dire Maul (North)",

    -- Dire Maul (West)
    ["DMWHelnurath"] = "Dire Maul (West)",
    ["DMWIllyannaRavenoak"] = "Dire Maul (West)",
    ["DMWImmolthar"] = "Dire Maul (West)",
    ["DMWMagisterKalendris"] = "Dire Maul (West)",
    ["DMWPrinceTortheldrin"] = "Dire Maul (West)",
    ["DMWRevanchion"] = "Dire Maul (West)",
    ["DMWShendralarProvisioner"] = "Dire Maul (West)",
    ["DMWTendrisWarpwood"] = "Dire Maul (West)",
    ["DMWTrash"] = "Dire Maul (West)",
    ["DMWTsuzee"] = "Dire Maul (West)",

    -- Dragonmaw Retreat
    ["DMRBroodmother"] = "Dragonmaw Retreat",
    ["DMRElderHollowblood"] = "Dragonmaw Retreat",
    ["DMRGarlok"] = "Dragonmaw Retreat",
    ["DMRGowlfang"] = "Dragonmaw Retreat",
    ["DMRHalgan"] = "Dragonmaw Retreat",
    ["DMROverlord"] = "Dragonmaw Retreat",
    ["DMRSearistrasz"] = "Dragonmaw Retreat",
    ["DMRSlagfist"] = "Dragonmaw Retreat",
    ["DMRTrash"] = "Dragonmaw Retreat",
    ["DMRWebMaster"] = "Dragonmaw Retreat",
    ["DMRZuluhed"] = "Dragonmaw Retreat",

    -- Druid
    ["PVPDruid"] = "Druid",
    ["T0Druid"] = "Druid",
    ["T2Druid"] = "Druid",

    -- Eastern Plaguelands
    ["Nerubian"] = "Eastern Plaguelands",

    -- Emerald Dragons
    ["DTrash"] = "Emerald Dragons",

    -- Emerald Sanctum
    ["ESErennius"] = "Emerald Sanctum",
    ["ESHardMode"] = "Emerald Sanctum",
    ["ESSolnius1"] = "Emerald Sanctum",
    ["ESTrash"] = "Emerald Sanctum",

    -- Gilneas City
    ["GCDustivanBlackcowl"] = "Gilneas City",
    ["GCGennGreymane"] = "Gilneas City",
    ["GCHarlowFamilyChest"] = "Gilneas City",
    ["GCHorsemasterLevvin"] = "Gilneas City",
    ["GCJudgeSutherland"] = "Gilneas City",
    ["GCMarshalMagnusGreystone"] = "Gilneas City",
    ["GCMatthiasHoltz"] = "Gilneas City",
    ["GCPackmasterRagetooth"] = "Gilneas City",
    ["GCTrash"] = "Gilneas City",

    -- Gnomeregan
    ["GnCrowdPummeler960"] = "Gnomeregan",
    ["GnDIAmbassador"] = "Gnomeregan",
    ["GnElectrocutioner6000"] = "Gnomeregan",
    ["GnGrubbis"] = "Gnomeregan",
    ["GnMekgineerThermaplugg"] = "Gnomeregan",
    ["GnNamdoBizzfizzle"] = "Gnomeregan",
    ["GnOutsideTrash"] = "Gnomeregan",
    ["GnPunchographA"] = "Gnomeregan",
    ["GnPunchographB"] = "Gnomeregan",
    ["GnPunchographC"] = "Gnomeregan",
    ["GnPunchographD"] = "Gnomeregan",
    ["GnTechbot"] = "Gnomeregan",
    ["GnTrash"] = "Gnomeregan",
    ["GnViscousFallout"] = "Gnomeregan",

    -- Hateforge Quarry
    ["HQCorrosis"] = "Hateforge Quarry",
    ["HQEngineerFiggles"] = "Hateforge Quarry",
    ["HQHargeshDoomcaller"] = "Hateforge Quarry",
    ["HQHatereaverAnnihilator"] = "Hateforge Quarry",
    ["HQHighForemanBargulBlackhammer"] = "Hateforge Quarry",
    ["HQTrash"] = "Hateforge Quarry",

    -- Hunter
    ["PVPHunter"] = "Hunter",
    ["T0Hunter"] = "Hunter",
    ["T2Hunter"] = "Hunter",

    -- Karazhan
    ["T35Druid"] = "Karazhan",
    ["T35Hunter"] = "Karazhan",
    ["T35Mage"] = "Karazhan",
    ["T35Paladin"] = "Karazhan",
    ["T35Priest"] = "Karazhan",
    ["T35Rogue"] = "Karazhan",
    ["T35Shaman"] = "Karazhan",
    ["T35Warlock"] = "Karazhan",
    ["T35Warrior"] = "Karazhan",

    -- Karazhan Crypt
    ["KCAlarus"] = "Karazhan Crypt",
    ["KCArchlichEnkhraz"] = "Karazhan Crypt",
    ["KCCommanderAndreon"] = "Karazhan Crypt",
    ["KCCorpsemuncher"] = "Karazhan Crypt",
    ["KCGuardCaptainGort"] = "Karazhan Crypt",
    ["KCHivaxxis"] = "Karazhan Crypt",
    ["KCMarrowspike"] = "Karazhan Crypt",
    ["KCTrash"] = "Karazhan Crypt",
    ["KCTreasure"] = "Karazhan Crypt",

    -- Lower Blackrock Spire
    ["LBRSBashguud"] = "Lower Blackrock Spire",
    ["LBRSCrystalFang"] = "Lower Blackrock Spire",
    ["LBRSDoomhowl"] = "Lower Blackrock Spire",
    ["LBRSFelguard"] = "Lower Blackrock Spire",
    ["LBRSGrayhoof"] = "Lower Blackrock Spire",
    ["LBRSGrimaxe"] = "Lower Blackrock Spire",
    ["LBRSHalycon"] = "Lower Blackrock Spire",
    ["LBRSHumanRemains"] = "Lower Blackrock Spire",
    ["LBRSOmokk"] = "Lower Blackrock Spire",
    ["LBRSPike"] = "Lower Blackrock Spire",
    ["LBRSSlavener"] = "Lower Blackrock Spire",
    ["LBRSSmolderweb"] = "Lower Blackrock Spire",
    ["LBRSSpirestoneBattleLord"] = "Lower Blackrock Spire",
    ["LBRSSpirestoneButcher"] = "Lower Blackrock Spire",
    ["LBRSSpirestoneLordMagus"] = "Lower Blackrock Spire",
    ["LBRSTrash"] = "Lower Blackrock Spire",
    ["LBRSVoone"] = "Lower Blackrock Spire",
    ["LBRSVosh"] = "Lower Blackrock Spire",
    ["LBRSWyrmthalak"] = "Lower Blackrock Spire",
    ["LBRSZigris"] = "Lower Blackrock Spire",

    -- Lower Karazhan Halls
    ["LKHBroodQueenAraxxna"] = "Lower Karazhan Halls",
    ["LKHClawlordHowlfang"] = "Lower Karazhan Halls",
    ["LKHEnchants"] = "Lower Karazhan Halls",
    ["LKHGrizikil"] = "Lower Karazhan Halls",
    ["LKHLordBlackwaldII"] = "Lower Karazhan Halls",
    ["LKHMoroes"] = "Lower Karazhan Halls",
    ["LKHRolfen"] = "Lower Karazhan Halls",
    ["LKHTrash"] = "Lower Karazhan Halls",

    -- Mage
    ["PVPMage"] = "Mage",
    ["T0Mage"] = "Mage",
    ["T2Mage"] = "Mage",

    -- Maraudon
    ["MaraCelebras"] = "Maraudon",
    ["MaraKhanGelk"] = "Maraudon",
    ["MaraKhanKolk"] = "Maraudon",
    ["MaraKhanMagra"] = "Maraudon",
    ["MaraKhanMaraudos"] = "Maraudon",
    ["MaraKhanVeng"] = "Maraudon",
    ["MaraLandslide"] = "Maraudon",
    ["MaraLordVyletongue"] = "Maraudon",
    ["MaraMeshlok"] = "Maraudon",
    ["MaraNamelesProphet"] = "Maraudon",
    ["MaraNoxxion"] = "Maraudon",
    ["MaraPrincessTheradras"] = "Maraudon",
    ["MaraRazorlash"] = "Maraudon",
    ["MaraRotgrip"] = "Maraudon",
    ["MaraTinkererGizlock"] = "Maraudon",
    ["MaraTrash"] = "Maraudon",

    -- Molten Core
    ["MCGarr"] = "Molten Core",
    ["MCGeddon"] = "Molten Core",
    ["MCGehennas"] = "Molten Core",
    ["MCGolemagg"] = "Molten Core",
    ["MCIncindis"] = "Molten Core",
    ["MCLucifron"] = "Molten Core",
    ["MCMagmadar"] = "Molten Core",
    ["MCMajordomo"] = "Molten Core",
    ["MCRANDOMBOSSDROPS"] = "Molten Core",
    ["MCRagnaros"] = "Molten Core",
    ["MCShazzrah"] = "Molten Core",
    ["MCSulfuron"] = "Molten Core",
    ["MCThaurissan"] = "Molten Core",
    ["MCTrashMobs"] = "Molten Core",
    ["MCTwins"] = "Molten Core",
    ["T1Druid"] = "Molten Core",
    ["T1Hunter"] = "Molten Core",
    ["T1Mage"] = "Molten Core",
    ["T1Paladin"] = "Molten Core",
    ["T1Priest"] = "Molten Core",
    ["T1Rogue"] = "Molten Core",
    ["T1Shaman"] = "Molten Core",
    ["T1Warlock"] = "Molten Core",
    ["T1Warrior"] = "Molten Core",

    -- Moomoo Grove
    ["CowKing"] = "Moomoo Grove",

    -- Naxxramas
    ["NAXAnubRekhan"] = "Naxxramas",
    ["NAXGluth"] = "Naxxramas",
    ["NAXGothiktheHarvester"] = "Naxxramas",
    ["NAXGrandWidowFaerlina"] = "Naxxramas",
    ["NAXGrobbulus"] = "Naxxramas",
    ["NAXHeigantheUnclean"] = "Naxxramas",
    ["NAXInstructorRazuvious"] = "Naxxramas",
    ["NAXKelThuzard"] = "Naxxramas",
    ["NAXLoatheb"] = "Naxxramas",
    ["NAXMaexxna"] = "Naxxramas",
    ["NAXNoththePlaguebringer"] = "Naxxramas",
    ["NAXPatchwerk"] = "Naxxramas",
    ["NAXSapphiron"] = "Naxxramas",
    ["NAXThaddius"] = "Naxxramas",
    ["NAXTheFourHorsemen"] = "Naxxramas",
    ["NAXTrash"] = "Naxxramas",
    ["T3Druid"] = "Naxxramas",
    ["T3Hunter"] = "Naxxramas",
    ["T3Mage"] = "Naxxramas",
    ["T3Paladin"] = "Naxxramas",
    ["T3Priest"] = "Naxxramas",
    ["T3Rogue"] = "Naxxramas",
    ["T3Shaman"] = "Naxxramas",
    ["T3Warlock"] = "Naxxramas",
    ["T3Warrior"] = "Naxxramas",

    -- Onyxia's Lair
    ["Onyxia"] = "Onyxia's Lair",

    -- Paladin
    ["PVPPaladin"] = "Paladin",
    ["T0Paladin"] = "Paladin",
    ["T2Paladin"] = "Paladin",

    -- Priest
    ["PVPPriest"] = "Priest",
    ["T0Priest"] = "Priest",
    ["T2Priest"] = "Priest",

    -- Ragefire Chasm
    ["RFCBazzalan"] = "Ragefire Chasm",
    ["RFCJergosh"] = "Ragefire Chasm",
    ["RFCOggleflint"] = "Ragefire Chasm",
    ["RFCTaragaman"] = "Ragefire Chasm",

    -- Razorfen Downs
    ["RFDAmnennar"] = "Razorfen Downs",
    ["RFDDeathProphet"] = "Razorfen Downs",
    ["RFDGlutton"] = "Razorfen Downs",
    ["RFDHenryStern"] = "Razorfen Downs",
    ["RFDLadyF"] = "Razorfen Downs",
    ["RFDMordreshFireEye"] = "Razorfen Downs",
    ["RFDPlaguemaw"] = "Razorfen Downs",
    ["RFDRagglesnout"] = "Razorfen Downs",
    ["RFDTrash"] = "Razorfen Downs",
    ["RFDTutenkash"] = "Razorfen Downs",

    -- Razorfen Kraul
    ["RFKAgathelos"] = "Razorfen Kraul",
    ["RFKAggem"] = "Razorfen Kraul",
    ["RFKBlindHunter"] = "Razorfen Kraul",
    ["RFKCharlgaRazorflank"] = "Razorfen Kraul",
    ["RFKDeathSpeakerJargba"] = "Razorfen Kraul",
    ["RFKEarthcallerHalmgar"] = "Razorfen Kraul",
    ["RFKOverlordRamtusk"] = "Razorfen Kraul",
    ["RFKRazorfenSpearhide"] = "Razorfen Kraul",
    ["RFKRotthorn"] = "Razorfen Kraul",
    ["RFKTrash"] = "Razorfen Kraul",

    -- Rogue
    ["PVPRogue"] = "Rogue",
    ["Poisons1"] = "Rogue",
    ["T0Rogue"] = "Rogue",
    ["T2Rogue"] = "Rogue",

    -- Ruins of Ahn'Qiraj
    ["AQ20Andorov"] = "Ruins of Ahn'Qiraj",
    ["AQ20Ayamiss"] = "Ruins of Ahn'Qiraj",
    ["AQ20Buru"] = "Ruins of Ahn'Qiraj",
    ["AQ20CAPTAIN"] = "Ruins of Ahn'Qiraj",
    ["AQ20ClassBooks"] = "Ruins of Ahn'Qiraj",
    ["AQ20Druid"] = "Ruins of Ahn'Qiraj",
    ["AQ20Enchants"] = "Ruins of Ahn'Qiraj",
    ["AQ20Hunter"] = "Ruins of Ahn'Qiraj",
    ["AQ20Kurinnaxx"] = "Ruins of Ahn'Qiraj",
    ["AQ20Mage"] = "Ruins of Ahn'Qiraj",
    ["AQ20Moam"] = "Ruins of Ahn'Qiraj",
    ["AQ20Ossirian"] = "Ruins of Ahn'Qiraj",
    ["AQ20Paladin"] = "Ruins of Ahn'Qiraj",
    ["AQ20Priest"] = "Ruins of Ahn'Qiraj",
    ["AQ20Rajaxx"] = "Ruins of Ahn'Qiraj",
    ["AQ20Rogue"] = "Ruins of Ahn'Qiraj",
    ["AQ20Shaman"] = "Ruins of Ahn'Qiraj",
    ["AQ20Trash"] = "Ruins of Ahn'Qiraj",
    ["AQ20Warlock"] = "Ruins of Ahn'Qiraj",
    ["AQ20Warrior"] = "Ruins of Ahn'Qiraj",

    -- Scarlet Monastery (Armory)
    ["SMATrash"] = "Scarlet Monastery (Armory)",
    ["SMHerod"] = "Scarlet Monastery (Armory)",
    ["SMQuartermaster"] = "Scarlet Monastery (Armory)",

    -- Scarlet Monastery (Cathedral)
    ["SMCTrash"] = "Scarlet Monastery (Cathedral)",
    ["SMFairbanks"] = "Scarlet Monastery (Cathedral)",
    ["SMMograine"] = "Scarlet Monastery (Cathedral)",
    ["SMWhitemane"] = "Scarlet Monastery (Cathedral)",

    -- Scarlet Monastery (Graveyard)
    ["SMAzshir"] = "Scarlet Monastery (Graveyard)",
    ["SMBloodmageThalnos"] = "Scarlet Monastery (Graveyard)",
    ["SMDukeDreadmoore"] = "Scarlet Monastery (Graveyard)",
    ["SMFallenChampion"] = "Scarlet Monastery (Graveyard)",
    ["SMGTrash"] = "Scarlet Monastery (Graveyard)",
    ["SMIronspine"] = "Scarlet Monastery (Graveyard)",
    ["SMScorn"] = "Scarlet Monastery (Graveyard)",
    ["SMVishas"] = "Scarlet Monastery (Graveyard)",

    -- Scarlet Monastery (Library)
    ["SMBrotherWystan"] = "Scarlet Monastery (Library)",
    ["SMDoan"] = "Scarlet Monastery (Library)",
    ["SMDoansBox"] = "Scarlet Monastery (Library)",
    ["SMHoundmasterLoksey"] = "Scarlet Monastery (Library)",
    ["SMLTrash"] = "Scarlet Monastery (Library)",

    -- Scholomance
    ["SCHOLOBlood"] = "Scholomance",
    ["SCHOLODarkmasterGandling"] = "Scholomance",
    ["SCHOLODeathKnight"] = "Scholomance",
    ["SCHOLODoctorTheolenKrastinov"] = "Scholomance",
    ["SCHOLOInstructorMalicia"] = "Scholomance",
    ["SCHOLOJandiceBarov"] = "Scholomance",
    ["SCHOLOKirtonostheHerald"] = "Scholomance",
    ["SCHOLOKormok"] = "Scholomance",
    ["SCHOLOLadyIlluciaBarov"] = "Scholomance",
    ["SCHOLOLordAlexeiBarov"] = "Scholomance",
    ["SCHOLOLordBlackwood"] = "Scholomance",
    ["SCHOLOLorekeeperPolkelt"] = "Scholomance",
    ["SCHOLOMarduk"] = "Scholomance",
    ["SCHOLORasFrostwhisper"] = "Scholomance",
    ["SCHOLORattlegore"] = "Scholomance",
    ["SCHOLOTheRavenian"] = "Scholomance",
    ["SCHOLOTrash"] = "Scholomance",
    ["SCHOLOVectus"] = "Scholomance",

    -- Shadowfang Keep
    ["SFKArchmageArugal"] = "Shadowfang Keep",
    ["SFKArugalsVoidwalker"] = "Shadowfang Keep",
    ["SFKBookofUr"] = "Shadowfang Keep",
    ["SFKDeathswornCaptain"] = "Shadowfang Keep",
    ["SFKFelSteed"] = "Shadowfang Keep",
    ["SFKFenrustheDevourer"] = "Shadowfang Keep",
    ["SFKJordansHammer"] = "Shadowfang Keep",
    ["SFKOdotheBlindwatcher"] = "Shadowfang Keep",
    ["SFKPrelate"] = "Shadowfang Keep",
    ["SFKRazorclawtheButcher"] = "Shadowfang Keep",
    ["SFKRethilgore"] = "Shadowfang Keep",
    ["SFKSever"] = "Shadowfang Keep",
    ["SFKSilverlaine"] = "Shadowfang Keep",
    ["SFKSpringvale"] = "Shadowfang Keep",
    ["SFKTrash"] = "Shadowfang Keep",
    ["SFKWolfMasterNandos"] = "Shadowfang Keep",

    -- Shaman
    ["PVPShaman"] = "Shaman",
    ["T0Shaman"] = "Shaman",
    ["T2Shaman"] = "Shaman",

    -- Stormwind Vault
    ["SWVAszoshGrimflame"] = "Stormwind Vault",
    ["SWVBlackBride"] = "Stormwind Vault",
    ["SWVDamian"] = "Stormwind Vault",
    ["SWVThamGrarr"] = "Stormwind Vault",
    ["SWVTrash"] = "Stormwind Vault",
    ["SWVVaultArmoryEquipment"] = "Stormwind Vault",
    ["SWVVolkanCruelblade"] = "Stormwind Vault",

    -- Stormwrought Ruins
    ["SWRChieftain"] = "Stormwrought Ruins",
    ["SWRDagar"] = "Stormwrought Ruins",
    ["SWRDeathlord"] = "Stormwrought Ruins",
    ["SWRDukeBalor"] = "Stormwrought Ruins",
    ["SWREldermaw"] = "Stormwrought Ruins",
    ["SWRLadyDrazare"] = "Stormwrought Ruins",
    ["SWRLibrarian"] = "Stormwrought Ruins",
    ["SWRMergothid"] = "Stormwrought Ruins",
    ["SWRMycellakos"] = "Stormwrought Ruins",
    ["SWROronok"] = "Stormwrought Ruins",
    ["SWRRemains"] = "Stormwrought Ruins",
    ["SWRSubjugator"] = "Stormwrought Ruins",
    ["SWRTrash"] = "Stormwrought Ruins",

    -- Stratholme
    ["STRATArchivistGalford"] = "Stratholme",
    ["STRATAtiesh"] = "Stratholme",
    ["STRATBSPlansCorruption"] = "Stratholme",
    ["STRATBSPlansSerenity"] = "Stratholme",
    ["STRATBalnazzar"] = "Stratholme",
    ["STRATBalzaphon"] = "Stratholme",
    ["STRATBaronRivendare"] = "Stratholme",
    ["STRATBaronessAnastari"] = "Stratholme",
    ["STRATBlackGuardSwordsmith"] = "Stratholme",
    ["STRATCannonMasterWilley"] = "Stratholme",
    ["STRATCrimsonHammersmith"] = "Stratholme",
    ["STRATFrasSiabi"] = "Stratholme",
    ["STRATHearthsingerForresten"] = "Stratholme",
    ["STRATMagistrateBarthilas"] = "Stratholme",
    ["STRATMalekithePallid"] = "Stratholme",
    ["STRATMalor"] = "Stratholme",
    ["STRATMalorsStrongbox"] = "Stratholme",
    ["STRATNerubenkan"] = "Stratholme",
    ["STRATPostmaster"] = "Stratholme",
    ["STRATRamsteintheGorger"] = "Stratholme",
    ["STRATSkull"] = "Stratholme",
    ["STRATSothosJarien"] = "Stratholme",
    ["STRATStonespine"] = "Stratholme",
    ["STRATStratholmeCourier"] = "Stratholme",
    ["STRATTheUnforgiven"] = "Stratholme",
    ["STRATTimmytheCruel"] = "Stratholme",
    ["STRATTrash"] = "Stratholme",

    -- Tanaris
    ["Ostarius"] = "Tanaris",

    -- Temple of Ahn'Qiraj
    ["AQ40CThun"] = "Temple of Ahn'Qiraj",
    ["AQ40Druid"] = "Temple of Ahn'Qiraj",
    ["AQ40Emperors"] = "Temple of Ahn'Qiraj",
    ["AQ40Fankriss"] = "Temple of Ahn'Qiraj",
    ["AQ40Huhuran"] = "Temple of Ahn'Qiraj",
    ["AQ40Hunter"] = "Temple of Ahn'Qiraj",
    ["AQ40Mage"] = "Temple of Ahn'Qiraj",
    ["AQ40Ouro"] = "Temple of Ahn'Qiraj",
    ["AQ40Paladin"] = "Temple of Ahn'Qiraj",
    ["AQ40Priest"] = "Temple of Ahn'Qiraj",
    ["AQ40Rogue"] = "Temple of Ahn'Qiraj",
    ["AQ40Sartura"] = "Temple of Ahn'Qiraj",
    ["AQ40Shaman"] = "Temple of Ahn'Qiraj",
    ["AQ40Skeram"] = "Temple of Ahn'Qiraj",
    ["AQ40Trash1"] = "Temple of Ahn'Qiraj",
    ["AQ40Trash2"] = "Temple of Ahn'Qiraj",
    ["AQ40Trio"] = "Temple of Ahn'Qiraj",
    ["AQ40Viscidus"] = "Temple of Ahn'Qiraj",
    ["AQ40Warlock"] = "Temple of Ahn'Qiraj",
    ["AQ40Warrior"] = "Temple of Ahn'Qiraj",
    ["AQEnchants"] = "Temple of Ahn'Qiraj",
    ["AQOpening"] = "Temple of Ahn'Qiraj",

    -- The Crescent Grove
    ["TCGFenektistheDeceiver"] = "The Crescent Grove",
    ["TCGGrovetenderEngryss"] = "The Crescent Grove",
    ["TCGHighPriestessAlathea"] = "The Crescent Grove",
    ["TCGKeeperRanathos"] = "The Crescent Grove",
    ["TCGMasterRaxxieth"] = "The Crescent Grove",
    ["TCGTrash"] = "The Crescent Grove",

    -- The Deadmines
    ["DMBrainwashedNoble"] = "The Deadmines",
    ["DMCaptainGreenskin"] = "The Deadmines",
    ["DMCookie"] = "The Deadmines",
    ["DMDefiasGunpowder"] = "The Deadmines",
    ["DMForemanThistlenettle"] = "The Deadmines",
    ["DMGilnid"] = "The Deadmines",
    ["DMHarvester"] = "The Deadmines",
    ["DMJaredVoss"] = "The Deadmines",
    ["DMMarisaduPaige"] = "The Deadmines",
    ["DMMinerJohnson"] = "The Deadmines",
    ["DMMrSmite"] = "The Deadmines",
    ["DMRhahkZor"] = "The Deadmines",
    ["DMSneed"] = "The Deadmines",
    ["DMSneedsShredder"] = "The Deadmines",
    ["DMTrash"] = "The Deadmines",
    ["DMVanCleef"] = "The Deadmines",

    -- The Stockade
    ["SWStBazil"] = "The Stockade",
    ["SWStBruegalIronknuckle"] = "The Stockade",
    ["SWStDextren"] = "The Stockade",
    ["SWStHamhock"] = "The Stockade",
    ["SWStKamDeepfury"] = "The Stockade",
    ["SWStTargorr"] = "The Stockade",
    ["SWStTrash"] = "The Stockade",

    -- The Sunken Temple
    ["STAtalalarion"] = "The Sunken Temple",
    ["STAvatarofHakkar"] = "The Sunken Temple",
    ["STBalconyMinibosses"] = "The Sunken Temple",
    ["STDreamscythe"] = "The Sunken Temple",
    ["STEranikus"] = "The Sunken Temple",
    ["STHazzas"] = "The Sunken Temple",
    ["STJammalan"] = "The Sunken Temple",
    ["STMorphaz"] = "The Sunken Temple",
    ["STOgom"] = "The Sunken Temple",
    ["STSpawnOfHakkar"] = "The Sunken Temple",
    ["STTrash"] = "The Sunken Temple",
    ["STWeaver"] = "The Sunken Temple",

    -- Thorium Brotherhood
    ["Thorium1"] = "Thorium Brotherhood",
    ["Thorium2"] = "Thorium Brotherhood",

    -- Uldaman
    ["UldAncientStoneKeeper"] = "Uldaman",
    ["UldArchaedas"] = "Uldaman",
    ["UldBaelog"] = "Uldaman",
    ["UldBaelogsChest"] = "Uldaman",
    ["UldEric"] = "Uldaman",
    ["UldGalgannFirehammer"] = "Uldaman",
    ["UldGarrettFamilyChest"] = "Uldaman",
    ["UldGrimlok"] = "Uldaman",
    ["UldIronaya"] = "Uldaman",
    ["UldKromStoutarmChest"] = "Uldaman",
    ["UldMagreganDeepshadow"] = "Uldaman",
    ["UldObsidianSentinel"] = "Uldaman",
    ["UldOlaf"] = "Uldaman",
    ["UldRevelosh"] = "Uldaman",
    ["UldShadowforgeCache"] = "Uldaman",
    ["UldShovelphlange"] = "Uldaman",
    ["UldTabletofRyuneh"] = "Uldaman",
    ["UldTabletofWill"] = "Uldaman",
    ["UldTrash"] = "Uldaman",

    -- Upper Blackrock Spire
    ["UBRSAnvilcrack"] = "Upper Blackrock Spire",
    ["UBRSBeast"] = "Upper Blackrock Spire",
    ["UBRSDrakkisath"] = "Upper Blackrock Spire",
    ["UBRSEmberseer"] = "Upper Blackrock Spire",
    ["UBRSFlame"] = "Upper Blackrock Spire",
    ["UBRSGyth"] = "Upper Blackrock Spire",
    ["UBRSRend"] = "Upper Blackrock Spire",
    ["UBRSRunewatcher"] = "Upper Blackrock Spire",
    ["UBRSSolakar"] = "Upper Blackrock Spire",
    ["UBRSTrash"] = "Upper Blackrock Spire",
    ["UBRSValthalak"] = "Upper Blackrock Spire",

    -- Upper Karazhan Halls
    ["UKHAnomalus"] = "Upper Karazhan Halls",
    ["UKHEcho"] = "Upper Karazhan Halls",
    ["UKHGnarlmoon"] = "Upper Karazhan Halls",
    ["UKHIncantagos"] = "Upper Karazhan Halls",
    ["UKHKing"] = "Upper Karazhan Halls",
    ["UKHKruul"] = "Upper Karazhan Halls",
    ["UKHMephistroth"] = "Upper Karazhan Halls",
    ["UKHRupturan"] = "Upper Karazhan Halls",
    ["UKHSanvTasdal"] = "Upper Karazhan Halls",
    ["UKHTrash"] = "Upper Karazhan Halls",

    -- Wailing Caverns
    ["WCBoahn"] = "Wailing Caverns",
    ["WCDeviateFaerieDragon"] = "Wailing Caverns",
    ["WCKalldanFelmoon"] = "Wailing Caverns",
    ["WCKresh"] = "Wailing Caverns",
    ["WCLadyAnacondra"] = "Wailing Caverns",
    ["WCLordCobrahn"] = "Wailing Caverns",
    ["WCLordPythas"] = "Wailing Caverns",
    ["WCLordSerpentis"] = "Wailing Caverns",
    ["WCMadMagglish"] = "Wailing Caverns",
    ["WCMutanus"] = "Wailing Caverns",
    ["WCSkum"] = "Wailing Caverns",
    ["WCTrash"] = "Wailing Caverns",
    ["WCTrigoretheLasher"] = "Wailing Caverns",
    ["WCVangros"] = "Wailing Caverns",
    ["WCVerdan"] = "Wailing Caverns",
    ["WCZandara"] = "Wailing Caverns",

    -- Wardens of Time
    ["Wardens1"] = "Wardens of Time",
    ["Wardens2"] = "Wardens of Time",

    -- Warlock
    ["PVPWarlock"] = "Warlock",
    ["T0Warlock"] = "Warlock",
    ["T2Warlock"] = "Warlock",

    -- Warrior
    ["PVPWarrior"] = "Warrior",
    ["T0Warrior"] = "Warrior",
    ["T2Warrior"] = "Warrior",

    -- Warsong Gulch
    ["WSGRepExalted4049"] = "Warsong Gulch",
    ["WSGRepExalted5059"] = "Warsong Gulch",
    ["WSGRepExalted60"] = "Warsong Gulch",
    ["WSGRepFriendly"] = "Warsong Gulch",
    ["WSGRepHonored1019"] = "Warsong Gulch",
    ["WSGRepHonored2029"] = "Warsong Gulch",
    ["WSGRepHonored3039"] = "Warsong Gulch",
    ["WSGRepHonored4049"] = "Warsong Gulch",
    ["WSGRepHonored5059"] = "Warsong Gulch",
    ["WSGRepRevered1019"] = "Warsong Gulch",
    ["WSGRepRevered2029"] = "Warsong Gulch",
    ["WSGRepRevered3039"] = "Warsong Gulch",
    ["WSGRepRevered4049"] = "Warsong Gulch",
    ["WSGRepRevered5059"] = "Warsong Gulch",

    -- World Epics
    ["WorldEpics1"] = "World Epics",
    ["WorldEpics2"] = "World Epics",
    ["WorldEpics3"] = "World Epics",

    -- Zandalar Tribe
    ["Zandalar1"] = "Zandalar Tribe",
    ["Zandalar2"] = "Zandalar Tribe",

    -- Zul'Farrak
    ["ZFAntusul"] = "Zul'Farrak",
    ["ZFChampion"] = "Zul'Farrak",
    ["ZFChiefUkorzSandscalp"] = "Zul'Farrak",
    ["ZFDustwraith"] = "Zul'Farrak",
    ["ZFGahzrilla"] = "Zul'Farrak",
    ["ZFHydromancerVelratha"] = "Zul'Farrak",
    ["ZFNekrumGutchewer"] = "Zul'Farrak",
    ["ZFSandfury"] = "Zul'Farrak",
    ["ZFSergeantBly"] = "Zul'Farrak",
    ["ZFSezzziz"] = "Zul'Farrak",
    ["ZFThekatheMartyr"] = "Zul'Farrak",
    ["ZFTrash"] = "Zul'Farrak",
    ["ZFWitchDoctorZumrah"] = "Zul'Farrak",
    ["ZFZeljeb"] = "Zul'Farrak",
    ["ZFZerillis"] = "Zul'Farrak",

    -- Zul'Gurub
    ["ZGArlokk"] = "Zul'Gurub",
    ["ZGDruid"] = "Zul'Gurub",
    ["ZGEnchants"] = "Zul'Gurub",
    ["ZGGahzranka"] = "Zul'Gurub",
    ["ZGGrilek"] = "Zul'Gurub",
    ["ZGHakkar"] = "Zul'Gurub",
    ["ZGHazzarah"] = "Zul'Gurub",
    ["ZGHunter"] = "Zul'Gurub",
    ["ZGJeklik"] = "Zul'Gurub",
    ["ZGJindo"] = "Zul'Gurub",
    ["ZGJinxedHoodooPile"] = "Zul'Gurub",
    ["ZGMage"] = "Zul'Gurub",
    ["ZGMandokir"] = "Zul'Gurub",
    ["ZGMarli"] = "Zul'Gurub",
    ["ZGMuddyChurningWaters"] = "Zul'Gurub",
    ["ZGPaladin"] = "Zul'Gurub",
    ["ZGPriest"] = "Zul'Gurub",
    ["ZGRenataki"] = "Zul'Gurub",
    ["ZGRogue"] = "Zul'Gurub",
    ["ZGShaman"] = "Zul'Gurub",
    ["ZGShared"] = "Zul'Gurub",
    ["ZGThekal"] = "Zul'Gurub",
    ["ZGTrash1"] = "Zul'Gurub",
    ["ZGTrash2"] = "Zul'Gurub",
    ["ZGVenoxis"] = "Zul'Gurub",
    ["ZGWarlock"] = "Zul'Gurub",
    ["ZGWarrior"] = "Zul'Gurub",
    ["ZGWushoolay"] = "Zul'Gurub",

}
